import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin-pr1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-10">
          <Sidebar />
          <div className="flex-1 py-10 pe-16 max-h-screen overflow-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
